/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package problemapasseonibus;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author SoldierJVX
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();

        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        new Thread(new Runnable() {
            @Override
            public void run() {
                mainCode();
            }
        }).start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstTela = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Problema Passe Ônibus");

        jScrollPane1.setViewportView(lstTela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainCode() {
        DateFormat formatter = new SimpleDateFormat("dd/MM/yy");

        try {

            Cartao card1 = new Cartao();
            SistemaPassagem sp;

            sp = new SistemaPassagem(new ValorPassagem(3.8, formatter.parse("01/01/18")), this.lstTela);

            //Carga de R$ 3,80
            card1.carregarCreditos(3.8, formatter.parse("02/02/18"));

            //Novo preço
            sp.novoValor(new ValorPassagem(4, formatter.parse("03/03/18")));

            sp.cobrarPassagem(card1);
            sp.cobrarPassagem(card1);

            //Carga de R$ 3,80
            card1.carregarCreditos(3.8, formatter.parse("04/04/18"));

            sp.cobrarPassagem(card1);

            //Carga de R$ 0,20
            card1.carregarCreditos(0.2, formatter.parse("05/04/18"));

            sp.cobrarPassagem(card1);
            sp.cobrarPassagem(card1);

        } catch (ParseException ex) {
            Logger.getLogger(ProblemaPasseOnibus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstTela;
    // End of variables declaration//GEN-END:variables
}
